device: rename variable 'link' to 'link_protocol'
This patch renames variable 'link' to 'link_protocol' in order to avoid
collision with the 'link' symbol exported by unistd.h, which causes the
following compilation error:

  qmi-device.c: In function 'process_open_flags':
  qmi-device.c:1513:32: error: declaration of 'link' shadows a global
  declaration [-Werror=shadow]