qmicli,dms: fix logic getting stored image result
The GetStoredImageResult must exist before getting into the array item
loop, so that we fill the contents of the struct when we find the
images (modem and pri) we were looking for.

This also fixes the build when -Werror=maybe-uninitialized is used:

    /var/lib/jenkins/workspace/libqmi/master-without-mbim/source/src/qmicli/qmicli-dms.c:2800:5: error: ‘result’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         g_task_return_pointer (task, result, (GDestroyNotify)get_stored_image_result_free);
         ^