mbimcli: add missing EOL in error print when closing device
    [09 ago 2020, 10:15:51] [Debug] [/dev/cdc-wdm1] Received message (translated)...
    >>>>>> Header:
    >>>>>>   length      = 16
    >>>>>>   type        = function-error (0x80000004)
    >>>>>>   transaction = 11
    >>>>>> Contents:
    >>>>>>   error = 'NotOpened' (0x00000005)

    error: couldn't close device: MBIM protocol error: NotOpened[09 ago 2020, 10:15:51] [Debug] [/dev/cdc-wdm1] channel destroyed