qmi-device: Fix -Wimplicit-fallthrough warnings.
qmi-device.c: In function ‘device_open_step’:
qmi-device.c:1866:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
    ctx->step++;
    ~~~~~~~~~^~

GCC checks for comments annotating intentional fallthrough, but it didn't
recognize "Fall down", so this patch tweaks it to say "Fall through".