mbimcli,basic-connect: fix key-value parser in --connect
  error: invalid auth protocol value given: 'PAP'

  (mbimcli:679): GLib-WARNING **: 09:34:02.333: GError set over the top of a previous GError or uninitialized memory.
  This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
  The overwriting error message was: unknown auth: 'PAP'
  Network start failed

The bug was introduced in 6c2d10eb0d645d0f72bfcd3b4c58cf39b4309211