mbimcli: new '--no-close' global option to keep the Device open
When launching a connection through mbimcli, we need to keep the MbimDevice
open, i.e. we should not explicitly close it, or the connection will also be
lost. E.g:

$ sudo mbimcli -d /dev/cdc-wdm0 --connect="Internet"
    [/dev/cdc-wdm0] Successfully connected
    [/dev/cdc-wdm0] Connection status:
    	      Session ID: '0'
    	Activation state: 'activated'
    	Voice call state: 'none'
    	         IP type: 'ipv4'
    	    Context type: 'internet'
    	   Network error: 'unknown'

$ sudo mbimcli -d /dev/cdc-wdm0 --disconnect="0"
    error: operation failed: ContextNotActivated

$ sudo mbimcli -d /dev/cdc-wdm0 --connect="Internet" --no-close
    [/dev/cdc-wdm0] Successfully connected
    [/dev/cdc-wdm0] Connection status:
    	      Session ID: '0'
    	Activation state: 'activated'
    	Voice call state: 'none'
    	         IP type: 'ipv4'
    	    Context type: 'internet'
    	   Network error: 'unknown'

$ sudo mbimcli -d /dev/cdc-wdm0 --disconnect="0"
[/dev/cdc-wdm0] Successfully disconnected
[/dev/cdc-wdm0] Connection status:
	      Session ID: '0'
	Activation state: 'deactivated'
	Voice call state: 'none'
	         IP type: 'default'
	    Context type: 'internet'
	   Network error: 'unknown'