qmicli,loc: fix printing sensor data usage
  qmicli-loc.c: In function 'position_report_received':
  qmicli-loc.c:563:84: error: implicit conversion from 'QmiLocSensorDataUsage' to 'QmiLocReliability' [-Werror=enum-conversion]
    563 |             g_print ("   sensor data usage: %s\n", qmi_loc_reliability_get_string (sensor_data_usage));
        |                                                                                    ^~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

(cherry picked from commit f44a09b3fd25df0c6131ff47a08a9d865ec5aa0d)